// src/presentation/controllers/PatientDoctorsController.js
import mongoose from "mongoose";
import Appointment from "../../infrastructure/database/models/Appointment.js";
import Doctor from "../../infrastructure/database/models/DoctorProfile.js";
import SharedUser from "../../infrastructure/database/models/SharedUser.js";

export class PatientDoctorsController {
  /**
   * GET /api/patient/my-doctors
   * Returns a list of unique doctors this patient has had consultations with.
   * Aggregates by doctorId, sums total consultations, and retrieves doctor profile details.
   */
  async getMyDoctors(req, res) {
    try {
      const patientUserId = req.user?.id || req.user?._id;
      if (!patientUserId) {
        return res.status(401).json({ success: false, message: "Unauthorized. User ID missing." });
      }

      const patientObjectId = new mongoose.Types.ObjectId(patientUserId);

      const pipeline = [
        {
          $match: {
            patientId: patientObjectId,
            status: "completed"
          }
        },
        {
          $sort: { appointmentDate: -1, createdAt: -1 }
        },
        {
          $group: {
            _id: "$doctorId",
            totalConsultations: { $sum: 1 },
            lastConsultationDate: { $first: "$appointmentDate" },
            lastConsultationTime: { $first: "$appointmentTime" },
            lastConsultationType: { $first: "$consultationType" }
          }
        },
        {
          $lookup: {
            from: "doctors",
            localField: "_id",
            foreignField: "_id",
            as: "doctorProfile"
          }
        },
        {
          $unwind: "$doctorProfile"
        },
        {
          $project: {
            _id: "$_id",
            doctorId: "$_id",
            firstName: "$doctorProfile.firstName",
            lastName: { $ifNull: ["$doctorProfile.lastName", ""] },
            name: {
              $concat: [
                "Dr. ",
                "$doctorProfile.firstName",
                " ",
                { $ifNull: ["$doctorProfile.lastName", ""] }
              ]
            },
            specialty: { $ifNull: ["$doctorProfile.specialty", "General Practice"] },
            avatarUrl: { $ifNull: ["$doctorProfile.avatarUrl", ""] },
            yearsOfExperience: { $ifNull: ["$doctorProfile.yearsOfExperience", 0] },
            rating: { $ifNull: ["$doctorProfile.rating", 0] },
            reviewCount: { $ifNull: ["$doctorProfile.reviewCount", 0] },
            consultationSettings: "$doctorProfile.consultationSettings",
            slotDuration: { $ifNull: ["$doctorProfile.slotDuration", 15] },
            timezone: { $ifNull: ["$doctorProfile.timezone", "Asia/Kolkata"] },
            totalConsultations: 1,
            lastConsultationDate: 1,
            lastConsultationTime: 1,
            lastConsultationType: 1
          }
        },
        {
          $sort: { lastConsultationDate: -1 }
        }
      ];

      const doctors = await Appointment.aggregate(pipeline);

      return res.status(200).json({
        success: true,
        count: doctors.length,
        doctors
      });
    } catch (error) {
      console.error("[PatientDoctorsController.getMyDoctors] Error:", error);
      return res.status(500).json({
        success: false,
        message: "Failed to retrieve consulted doctors directory.",
        error: error.message
      });
    }
  }

  /**
   * GET /api/patient/my-doctors/:doctorId/history
   * STRICT PRIVACY FILTER:
   * Enforces `{ doctorId: req.params.doctorId, patientId: req.user.id }`.
   * Returns consultations, prescriptions, and files specifically generated by THIS doctor for THIS patient.
   */
  async getDoctorHistory(req, res) {
    try {
      const { doctorId } = req.params;
      if (!doctorId || !mongoose.Types.ObjectId.isValid(doctorId)) {
        return res.status(400).json({ success: false, message: "A valid Doctor ID is required." });
      }

      const patientUserId = req.user?.id || req.user?._id;
      if (!patientUserId) {
        return res.status(401).json({ success: false, message: "Unauthorized. User ID missing." });
      }

      const doctorObjId = new mongoose.Types.ObjectId(doctorId);
      const patientObjId = new mongoose.Types.ObjectId(patientUserId);

      // 1. Retrieve Doctor Profile
      const doctor = await Doctor.findById(doctorObjId)
        .select(
          "firstName lastName specialty avatarUrl yearsOfExperience rating reviewCount consultationSettings qualifications workingHours bio phone timezone"
        )
        .lean();

      if (!doctor) {
        return res.status(404).json({ success: false, message: "Doctor not found." });
      }

      // 2. Strict Privacy Query: Only appointments between THIS patient and THIS doctor
      const appointments = await Appointment.find({
        doctorId: doctorObjId,
        patientId: patientObjId,
      })
        .sort({ appointmentDate: -1, createdAt: -1 })
        .select(
          "appointmentDate appointmentTime consultationType status fee feeBreakdown prescriptions consultationFiles clinicalNotes createdAt"
        )
        .lean();

      return res.status(200).json({
        success: true,
        doctor: {
          id: doctor._id,
          doctorId: doctor._id,
          name: `Dr. ${doctor.firstName} ${doctor.lastName || ""}`.trim(),
          firstName: doctor.firstName,
          lastName: doctor.lastName || "",
          specialty: doctor.specialty || "General Practice",
          avatarUrl: doctor.avatarUrl || "",
          yearsOfExperience: doctor.yearsOfExperience || 0,
          rating: doctor.rating || 0,
          reviewCount: doctor.reviewCount || 0,
          consultationSettings: doctor.consultationSettings || {},
          qualifications: doctor.qualifications || [],
          bio: doctor.bio || "",
          phone: doctor.phone || ""
        },
        totalConsultations: appointments.length,
        consultations: appointments.map((app) => ({
          id: app._id,
          appointmentId: app._id,
          appointmentDate: app.appointmentDate,
          appointmentTime: app.appointmentTime,
          consultationType: app.consultationType,
          status: app.status,
          fee: app.feeBreakdown?.totalFee || app.fee || 0,
          prescriptions: app.prescriptions || [],
          consultationFiles: app.consultationFiles || [],
          clinicalAdvice: app.clinicalNotes || "",
          createdAt: app.createdAt
        }))
      });
    } catch (error) {
      console.error("[PatientDoctorsController.getDoctorHistory] Error:", error);
      return res.status(500).json({
        success: false,
        message: "Failed to retrieve doctor consultation history.",
        error: error.message
      });
    }
  }
}
